### ISSUE TITLE
Leaking old credentials

### ISSUE THREAD

**Issue by mike-plivo** [krajeswaran/dotfiles#1]
Hi @krajeswaran ,

Looks like you have published some very old credentials we don't use for a long time:
https://github.com/krajeswaran/dotfiles/blob/7b1baa1ba9c5851018288f954a532ec27ccbf10d/pgcli/.config/pgcli/config#L144-L154

Can you delete them from your config file?

Thank you
Mike

**Comment by krajeswaran** [comment]
@mike-plivo Yikes, removed. Thx!
